/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ecoCoinSmartContractSol from "./EcoCoinSmartContract.sol";
export type { ecoCoinSmartContractSol };
import type * as nftSol from "./nft.sol";
export type { nftSol };
export type { EcoCoin } from "./EcoCoin";
